name: Build
on:
  workflow_call:
    inputs:
      repository:
        description: Repository to clone and build
        type: string
        default: athasdev/athas
      ref:
        description: Branch/tag/ref to build
        type: string
        required: true
  workflow_dispatch:
    inputs:
      repository:
        description: Repository to clone and build
        type: string
        default: athasdev/athas
      ref:
        description: Branch/tag/ref to build
        type: string
        default: master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Athas
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}
          path: athas

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Rust dependencies
        run: |
          rustup target add x86_64-pc-windows-msvc

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            athas/src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('athas/**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('athas/**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install frontend dependencies
        working-directory: ./athas
        run: bun install

      - name: Build Tauri application
        working-directory: ./athas
        run: bun run tauri build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-windows-${{ inputs.ref }}
          path: |
            athas/src-tauri/target/release/bundle/msi/*.msi
            athas/src-tauri/target/release/bundle/nsis/*.exe
          retention-days: 30
